scheme: "MoonPunk"
author: "DisguisedPigeon"
base00: "#1A1B26"
base01: "#24283B"
base02: "#2E3250"
base03: "#565F89"
base04: "#A9B1D6"
base05: "#C0CAF5"
base06: "#E0E3FF"
base07: "#F8F8FF"
base08: "#F7768E"
base09: "#FF9E64"
base0A: "#E0AF68"
base0B: "#9ECE6A"
base0C: "#73DACA"
base0D: "#7AA2F7"
base0E: "#BB9AF7"
base0F: "#C56EC7"
