{ inputs, ... }:
{
  flake-file.inputs.noctalia = {
    url = "github:noctalia-dev/noctalia-shell";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  flake.aspects.noctalia.homeManager =
    { pkgs, ... }:
    {
      imports = [ inputs.noctalia.homeModules.default ];

      home.packages = [
        inputs.noctalia.packages.${pkgs.stdenv.hostPlatform.system}.default
      ];

      stylix.targets.noctalia-shell.enable = false;

      programs.noctalia-shell = {
        enable = true;
        # Autogenerated by the systemd service as json.
        # Re-formatted to nix through nvim magic
        # Pass the NOCTALIA_SETTINGS_FALLBACK env var to noctalia, pointing to the destination json file.

        settings = {
          appLauncher = {
            autoPasteClipboard = false;
            clipboardWrapText = true;
            customLaunchPrefix = "";
            customLaunchPrefixEnabled = false;
            enableClipPreview = true;
            enableClipboardHistory = true;
            iconMode = "tabler";
            ignoreMouseInput = true;
            pinnedApps = [ ];
            position = "top_center";
            screenshotAnnotationTool = "";
            showCategories = false;
            showIconBackground = true;
            sortByMostUsed = true;
            terminalCommand = "wezterm -e";
            useApp2Unit = false;
            viewMode = "list";
          };
          audio = {
            cavaFrameRate = 120;
            mprisBlacklist = [ ];
            preferredPlayer = "vlc";
            visualizerType = "linear";
            volumeOverdrive = false;
            volumeStep = 5;
          };
          bar = {
            backgroundOpacity = 0;
            capsuleOpacity = 1;
            density = "comfortable";
            exclusive = true;
            floating = true;
            hideOnOverview = false;
            marginHorizontal = 0;
            marginVertical = 0;
            monitors = [ ];
            outerCorners = true;
            position = "top";
            showCapsule = true;
            showOutline = false;
            useSeparateOpacity = true;
            widgets = {
              center = [
                {
                  customFont = "";
                  formatHorizontal = "HH:mm ddd, MMM dd";
                  formatVertical = "HH mm - dd MM";
                  id = "Clock";
                  tooltipFormat = "HH:mm ddd, MMM dd";
                  useCustomFont = false;
                  usePrimaryColor = false;
                }
              ];
              left = [
                {
                  icon = "rocket";
                  id = "Launcher";
                  usePrimaryColor = false;
                }
                {
                  defaultSettings = {
                    hideBackground = false;
                    minimumThreshold = 10;
                  };
                  id = "plugin:catwalk";
                }
                {
                  characterCount = 1;
                  colorizeIcons = false;
                  enableScrollWheel = true;
                  followFocusedScreen = false;
                  groupedBorderOpacity = 1;
                  hideUnoccupied = true;
                  iconScale = 0.8;
                  id = "Workspace";
                  labelMode = "index";
                  showApplications = false;
                  showLabelsOnlyWhenOccupied = false;
                  unfocusedIconsOpacity = 1;
                }
                {
                  colorizeIcons = false;
                  hideMode = "hidden";
                  id = "ActiveWindow";
                  maxWidth = 540;
                  scrollingMode = "hover";
                  showIcon = true;
                  useFixedWidth = false;
                }
              ];
              right = [
                {
                  blacklist = [ ];
                  colorizeIcons = false;
                  drawerEnabled = true;
                  hidePassive = false;
                  id = "Tray";
                  pinned = [ ];
                }
                {
                  defaultSettings = {
                    autoStartBreaks = false;
                    autoStartWork = false;
                    compactMode = false;
                    longBreakDuration = 15;
                    sessionsBeforeLongBreak = 4;
                    shortBreakDuration = 5;
                    workDuration = 25;
                  };
                  id = "plugin:pomodoro";
                }
                {
                  displayMode = "onhover";
                  id = "Volume";
                  middleClickCommand = "pwvucontrol || pavucontrol";
                }
                {
                  displayMode = "alwaysHide";
                  id = "Brightness";
                }
                {
                  defaultSettings = { };
                  id = "plugin:mangowc-layout-switcher";
                }
                {
                  defaultSettings = {
                    feeds = [ ];
                    markAsReadOnClick = true;
                    maxItemsPerFeed = 10;
                    readItems = [ ];
                    showOnlyUnread = false;
                    updateInterval = 600;
                  };
                  id = "plugin:rss-feed";
                }
                {
                  hideWhenZero = true;
                  id = "NotificationHistory";
                  showUnreadBadge = true;
                }
                {
                  deviceNativePath = "";
                  displayMode = "alwaysShow";
                  hideIfNotDetected = true;
                  id = "Battery";
                  showNoctaliaPerformance = true;
                  showPowerProfiles = true;
                  warningThreshold = 25;
                }
                {
                  defaultSettings = {
                    hideInactive = false;
                    removeMargins = false;
                  };
                  id = "plugin:privacy-indicator";
                }
                {
                  compactMode = true;
                  diskPath = "/";
                  id = "SystemMonitor";
                  showCpuTemp = true;
                  showCpuUsage = true;
                  showDiskUsage = false;
                  showGpuTemp = false;
                  showLoadAverage = false;
                  showMemoryAsPercent = false;
                  showMemoryUsage = true;
                  showNetworkStats = false;
                  useMonospaceFont = true;
                  usePrimaryColor = false;
                }
                {
                  colorizeDistroLogo = false;
                  colorizeSystemIcon = "secondary";
                  customIconPath = "";
                  enableColorization = true;
                  icon = "noctalia";
                  id = "ControlCenter";
                  useDistroLogo = true;
                }
              ];
            };
          };
          brightness = {
            brightnessStep = 5;
            enableDdcSupport = true;
            enforceMinimum = false;
          };
          calendar = {
            cards = [
              {
                enabled = true;
                id = "calendar-header-card";
              }
              {
                enabled = true;
                id = "calendar-month-card";
              }
              {
                enabled = true;
                id = "weather-card";
              }
            ];
          };
          colorSchemes = {
            darkMode = true;
            manualSunrise = "06:30";
            manualSunset = "18:30";
            matugenSchemeType = "scheme-fruit-salad";
            predefinedScheme = "Rose Pine";
            schedulingMode = "location";
            useWallpaperColors = false;
          };
          controlCenter = {
            cards = [
              {
                enabled = true;
                id = "profile-card";
              }
              {
                enabled = true;
                id = "media-sysmon-card";
              }
              {
                enabled = true;
                id = "audio-card";
              }
              {
                enabled = true;
                id = "brightness-card";
              }
              {
                enabled = true;
                id = "shortcuts-card";
              }
              {
                enabled = true;
                id = "weather-card";
              }
            ];
            diskPath = "/";
            position = "close_to_bar_button";
            shortcuts = {
              left = [
                { id = "Network"; }
                { id = "Bluetooth"; }
                { id = "WiFi"; }
                { id = "DarkMode"; }
                { id = "WallpaperSelector"; }
              ];
              right = [
                { id = "Notifications"; }
                { id = "PowerProfile"; }
                { id = "KeepAwake"; }
                { id = "NightLight"; }
                {
                  enableOnStateLogic = false;
                  generalTooltipText = "Custom Button";
                  icon = "heart";
                  id = "CustomButton";
                  onClicked = "";
                  onMiddleClicked = "";
                  onRightClicked = "";
                  stateChecks = [ ];
                }
              ];
            };
          };
          desktopWidgets = {
            enabled = true;
            gridSnap = true;
            monitorWidgets = [
              {
                name = "HDMI-A-1";
                widgets = [
                  {
                    clockStyle = "binary";
                    customFont = "Maple Mono NF";
                    format = "HH:mm\\nd MMMM yyyy";
                    id = "Clock";
                    roundedCorners = true;
                    scale = 1;
                    showBackground = false;
                    useCustomFont = true;
                    usePrimaryColor = true;
                    x = 880;
                    y = 980;
                  }
                  {
                    hideMode = "hidden";
                    id = "MediaPlayer";
                    roundedCorners = true;
                    scale = 1;
                    showAlbumArt = true;
                    showBackground = false;
                    showButtons = true;
                    showVisualizer = false;
                    visualizerType = "linear";
                    x = 20;
                    y = 980;
                  }
                ];
              }
            ];
          };
          dock = {
            animationSpeed = 1;
            backgroundOpacity = 0.8;
            colorizeIcons = false;
            deadOpacity = 1;
            displayMode = "always_visible";
            enabled = false;
            floatingRatio = 0;
            inactiveIndicators = true;
            monitors = [ ];
            onlySameOutput = true;
            pinnedApps = [ ];
            pinnedStatic = false;
            position = "bottom";
            size = 1;
          };
          general = {
            allowPanelsOnScreenWithoutBar = true;
            animationDisabled = false;
            animationSpeed = 1;
            avatarImage = "/home/dpigeon/.face.png";
            boxRadiusRatio = 1;
            compactLockScreen = false;
            dimmerOpacity = 0.25;
            enableShadows = true;
            forceBlackScreenCorners = false;
            iRadiusRatio = 0.25;
            language = "en";
            lockOnSuspend = true;
            radiusRatio = 0.25;
            scaleRatio = 1;
            screenRadiusRatio = 1;
            shadowDirection = "bottom";
            shadowOffsetX = 0;
            shadowOffsetY = 3;
            showChangelogOnStartup = true;
            showHibernateOnLockScreen = true;
            showScreenCorners = false;
            showSessionButtonsOnLockScreen = false;
            telemetryEnabled = true;
          };
          hooks = {
            darkModeChange = "";
            enabled = false;
            performanceModeDisabled = "";
            performanceModeEnabled = "";
            screenLock = "";
            screenUnlock = "";
            wallpaperChange = "";
          };
          location = {
            analogClockInCalendar = true;
            firstDayOfWeek = 1;
            hideWeatherCityName = false;
            hideWeatherTimezone = false;
            name = "Santiago, Spain";
            showCalendarEvents = true;
            showCalendarWeather = true;
            showWeekNumberInCalendar = true;
            use12hourFormat = false;
            useFahrenheit = false;
            weatherEnabled = true;
            weatherShowEffects = true;
          };
          network = {
            bluetoothDetailsViewMode = "grid";
            bluetoothHideUnnamedDevices = false;
            bluetoothRssiPollIntervalMs = 10000;
            bluetoothRssiPollingEnabled = false;
            wifiDetailsViewMode = "grid";
            wifiEnabled = true;
          };
          nightLight = {
            autoSchedule = false;
            dayTemp = "6500";
            enabled = false;
            forced = false;
            manualSunrise = "06:30";
            manualSunset = "18:30";
            nightTemp = "5592";
          };
          notifications = {
            backgroundOpacity = 0.8;
            criticalUrgencyDuration = 15;
            enableKeyboardLayoutToast = true;
            enabled = true;
            location = "top_right";
            lowUrgencyDuration = 3;
            monitors = [ ];
            normalUrgencyDuration = 8;
            overlayLayer = true;
            respectExpireTimeout = true;
            saveToHistory = {
              critical = true;
              low = true;
              normal = true;
            };
            sounds = {
              criticalSoundFile = "";
              enabled = true;
              excludedApps = "discord;firefox;chrome;chromium;edge";
              lowSoundFile = "";
              normalSoundFile = "";
              separateSounds = false;
              volume = 0.5;
            };
          };
          osd = {
            autoHideMs = 2000;
            backgroundOpacity = 1;
            enabled = true;
            enabledTypes = [
              0
              1
              2
              3
            ];
            location = "top_right";
            monitors = [ ];
            overlayLayer = true;
          };
          sessionMenu = {
            countdownDuration = 5000;
            enableCountdown = true;
            largeButtonsLayout = "single-row";
            largeButtonsStyle = true;
            position = "center";
            powerOptions = [
              {
                action = "lock";
                command = "";
                countdownEnabled = true;
                enabled = true;
              }
              {
                action = "suspend";
                command = "";
                countdownEnabled = true;
                enabled = true;
              }
              {
                action = "hibernate";
                command = "";
                countdownEnabled = true;
                enabled = true;
              }
              {
                action = "reboot";
                command = "";
                countdownEnabled = true;
                enabled = true;
              }
              {
                action = "logout";
                command = "";
                countdownEnabled = true;
                enabled = true;
              }
              {
                action = "shutdown";
                command = "";
                countdownEnabled = true;
                enabled = true;
              }
            ];
            showHeader = true;
            showNumberLabels = true;
          };
          settingsVersion = 40;
          systemMonitor = {
            cpuCriticalThreshold = 90;
            cpuPollingInterval = 3000;
            cpuWarningThreshold = 80;
            criticalColor = "#eb6f92";
            diskCriticalThreshold = 85;
            diskPollingInterval = 3000;
            diskWarningThreshold = 80;
            enableDgpuMonitoring = false;
            externalMonitor = "resources || missioncenter || jdsystemmonitor || corestats || system-monitoring-center || gnome-system-monitor || plasma-systemmonitor || mate-system-monitor || ukui-system-monitor || deepin-system-monitor || pantheon-system-monitor";
            gpuCriticalThreshold = 90;
            gpuPollingInterval = 3000;
            gpuWarningThreshold = 80;
            loadAvgPollingInterval = 3000;
            memCriticalThreshold = 90;
            memPollingInterval = 3000;
            memWarningThreshold = 80;
            networkPollingInterval = 3000;
            tempCriticalThreshold = 90;
            tempPollingInterval = 3000;
            tempWarningThreshold = 80;
            useCustomColors = false;
            warningColor = "#31748f";
          };
          templates = {
            activeTemplates = [ ];
            enableUserTemplates = false;
          };
          ui = {
            bluetoothDetailsViewMode = "grid";
            bluetoothHideUnnamedDevices = false;
            boxBorderEnabled = true;
            fontDefault = "Maple Mono NF";
            fontDefaultScale = 1;
            fontFixed = "Maple Mono NF";
            fontFixedScale = 1;
            networkPanelView = "wifi";
            panelBackgroundOpacity = 0.9;
            panelsAttachedToBar = false;
            settingsPanelMode = "centered";
            tooltipsEnabled = true;
            wifiDetailsViewMode = "grid";
          };
          wallpaper = {
            directory = "/home/dpigeon/.local/share/backgrounds";
            enableMultiMonitorDirectories = false;
            enabled = true;
            fillColor = "#000000";
            fillMode = "crop";
            hideWallpaperFilenames = false;
            monitorDirectories = [ ];
            overviewEnabled = false;
            panelPosition = "follow_bar";
            randomEnabled = true;
            randomIntervalSec = 9000;
            recursiveSearch = false;
            setWallpaperOnAllMonitors = true;
            solidColor = "#1a1a2e";
            transitionDuration = 1500;
            transitionEdgeSmoothness = 0.05;
            transitionType = "random";
            useSolidColor = false;
            useWallhaven = false;
            wallhavenApiKey = "";
            wallhavenCategories = "111";
            wallhavenOrder = "desc";
            wallhavenPurity = "100";
            wallhavenQuery = "";
            wallhavenRatios = "";
            wallhavenResolutionHeight = "";
            wallhavenResolutionMode = "atleast";
            wallhavenResolutionWidth = "";
            wallhavenSorting = "relevance";
            wallpaperChangeMode = "random";
          };
        };
      };
    };
}
